sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Q9ATzgRVcVJKeUQX76lZ75TBt5T+nCJuDQE+ZVsApvA2Wjqt0G+Of/migdskQg3kynREZ8Le+DLUha718SDGx1jv90lGadnVjy075cuKFUpoR1odLZZweMe4hN2+owKeFBUZgkic2wyqG/RLcehe1eDX9ZnwnsOw/SxjxLDA7qGY6djv10YX5od1oHYFRukBOcNQsURvnJXeqCYgoSj+rMLIZlaWY0IfM2LJIrEc7T0By9EFi6Lx5O1YkDiY22lYJdSugkp0Bk6aQZ8WBHMPccLZWsL1w3gjuHND0GyyPIvgs3H5XXdW+4Tk5z7Lhh52MR30vVMt6f0CmVPJLFHMy7Fo5O49NaTTwzgDsw3rSM8wz4IE4GyRx2GOV2l7f9gT/QfkDDtQoR6/GB1AtXJwkOUQ6RHQu7eRhhkx+acURfqpDtf6xJLPR02FN5dDvjR2q1mtZ6sVvPgcoPdPhIX+s5DBmnMVUtga1cmxCv6h/8HiruQc0nPhOFi9JQtrelv0sEwJaFaHHGAx5/vIDAs8a+kO7lR6ucZ6wlfwc9IoH4YGPYi3OMfVINsa273zI4HRF0n2oYTDsHFy3gfJAq4ACXTTloC5vJcP5d1BSj3Me4DVjHdN7Qi00xiiB0BHykp7tHQr8+CYB2iqlGFijcqabQtB7kCj2pSW+j7O7b599kE=
  - secure: BiBUql7w8ZuQfWXHZGxpAt+OedkRquA3VgQFfKvmvaO+aNrowyjE08C3WMjiJg+1S4YnMtPq4xoJ9+IFVTcuwqZSxK+aO193XqmjTb7Xd6LOLk7tri0yn+KJLPdp9YaVacxyRUPDcHj1NL/iGR8oEjiSTRXwfqnGJq+F8tIM88Q0Nda29OG/QGdBt7FEwAVhZ1YmRZQFIFm0LlEsS5tNJOrAUlHwh7+pROVnaEZGMQMEoxUIXxVlanTNT52yfz1Qa7tRiGDnhn7dP4zgN4FjvS50pR8xs3xEEh+we6HjZNGPF7jSUj9dWvNob6aS7Vne/KJTz57zvt05duKXMNJVE0l7B8V9p9PplpL6O7lzbMuHJ4NxYUmWYJRdVfSWqH9FpwriG+vYMyc4WE8Y16q9F+uvPOyH6D1KGkhma0aoitVyxGnG24vM1nrU6NFSfP/QjrHxQ4cl5PvcngtDmWwZaQ+9yZkVmun7yP72ZH9/iIwKBKJMhrBzyVi1aohFHqsSybf+7DK/HgThLpB3YLNihF/pjFtrWTueWVt2YBuA9SeUoqIQCyKltRCMIsKo95UrfjDFM2rQHVR28F8Tlb8Lm0whdM7ukvPnCTOb8yjFdBpF32sLiSZwUmQyUSyTM+Q4LVUyoNmw2uJ+muQqu4qNsuq4L3RxpG6CHBKvlyGDd94=
