sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in deploy1.enc -out deploy_key1 -d; openssl aes-256-cbc -k "$password" -in deploy2.enc
  -out deploy_key2 -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
env:
  global:
  - secure: cbTmkeq61RHetF0kVaNr8c6b4c600NbFYj6qAOmMI880PBNbv8ZC/KLa7fPkZhGdnBUS/7bSu2cTfp6bQP4Nx6Zw7FsU1dpZolczzNBGZ6Vo4G/yU/6IGA+jEziz9W+4jCkcYY7cnblTvq2+4OPZFQjkRVwvDlvOPtYIEqA5Dqyr03whf7kOAnP2v5G1YehiUf9gihgJgss89j1sN9ZNZZAkUG1CBVTy5jad+jYw98HoEniZMCVUEKh4QJJ5K2pCqdHytue3IFp8dnImDJZc94CXwpWuJu8Ahncpp0YNrcW3TLuW9qyjfENwU+KN2Ilx0+Ku14I1/4gosCFFfi65lQrZG3N9VnZWZnrIHKHBEj0Y8Jaj1qtbZweFPyMb7O8TJoJKu/2LhS1ttp3YoFxyNsotjNnYVNIGzDzG9mq0Zcsy3ZBrP2W2a3mnfZ0ZtHtJm+s7FFfE5k+YrE47QJ2M7lGZjm7xk8fiPd+BVLedpMp6yKTU/5P776SNBwGoiLnyjBQfJ02w87zaCJ051OeM03FNmHPEbb9zLRK8XVrWtqDfT6TqzWdTsoLKDSubfC/5nX/qImdtVxUPXC+/bKuwploL41oZ2V1k4k7bxmxGsTt5/nHUWMhJquM0xRcBzbClXLcbkxhYeGif+xTKRKmx3BusvyRGL6UzW0UDz8p7hJk=
  - secure: mtLwMpEMEhDY8FuxNo+7oYkgMdlL2Ds9GhYhk5y8KEycuXO7+tgpBvAo1tpcgdqVNtIo45WFP77q2jPpqWxDHzow+y3UpJbyJ8e2TsxSa57mWK8SKuudcliAzHeFQ0FS+DEjRhTsHxo5Qnn0+17DK1abcCc192SWWkoKx47IVUoKaSOKU+4T8vnDK8e6x9ATiFL+3F+H7D8Z1yf9afAb28NTbR8SyxfQGKh+N0/DJgTFMokx1zY9f/RVgCiVl40WftZPH0XL8iSG5q8xWBCc/Y925lXPKUQhgJTHWwf+LK0L8CdXrFKAw5m9iQA5Ifv1JTj4Akb/vyQDWAhl0/Glr9eWQjmtdnzbJW2fyLexM2Y0YDjSfezv9+APRucA3sf/XEaiSbyIlnieGh3Uuolcaaq7AL8W6OTey6rxaN9sbWhoaxP4WYAqh4lu/lSUaFk44aWKJltOZs3Mk9LIa9++GxdpDlKPx7jvn8TtZ31Y7fDstKNEN3Zf/r7L05SjBp5JoV8fMjtM1nW6bWYJgGGpelLfAtsf9M247A3Mdz4ElYLBjdj4u9h331ZGb9OB4STfrNtqY020Zw0CkQRRP4IDUIG4b75Xq+Wwvoya/cHM7rps3sfXJ/2W4Vd98/1sqC9eWhLB92zHv3sOs/te5FEdBa3UQXYYeO4KLpEsgNNLJQk=
  - secure: sr7926OrYsaLPvGt4xFb2YUiwQ5Oq8VNjq6HA9dX63+2ww4TYYLQZd1HUiwAd4mhkEVTKZRZgyBEbzBoewpS72p8n8vF2kTerc9xee3m0585zHeuqpO7fJbVJXHi3iE+Plv0MBG+L/fLAp9j7U1xiFkwHEv87jfDtVsAggypqIUk9gc04MVqu3S612Fm0YI21VMDt5j1aWMd08qd1gJGi3raaHh8h/zLuT1sLf1WV5CXaFgCiFENjwox+3CTsPeXYdRLl/EB3xClpupi4sBse3QPfc2ma0nvC6aYV+/Az7+E90ewzMgOFfFMIbcy+hv5UVWLc5odscXeMK8H0jieDols53HP312h4GLck5ZufZCViDX1hbFZMJwvMNXQzEqZh9DNq9Uxw7YvP3JhIy0m1Nx4qVW2J7pbRiX3gM9Q+qgu4JV72gKMO3WfCjEWTPRvO1fRTgRH5t6nnQ3BEH20m6HR8rCcs4qVO2NGfI57MiXA8vt4f7trhfKbNH5zVCxkx3EnxGPi6K9z54n0vt/rY0o2czzH6TytvwpbNAwkVpgJxZbVk+jDLCt6guYg8hVT29UvzGd0gVYQes3zCZxFzng+uQT2lLSu85mFHZ1fBJDPBht6+pZwkKdM2IXuzcN4sQspohiN1ptWVAMdY9OjhimgNLi757HJkNx2FaYc3Kg=
